namespace TempestMonitor.Models;
public class VW_HourlyObservationSummary
{
    public int hours_back { get; set; }
    public int min_timestamp_local { get; set; }
    public int max_timestamp_local { get; set; }
    public float avg_timestamp_local { get; set; }
    public string min_timestamp_local_datetime { get; set; }
    public string max_timestamp_local_datetime { get; set; }
    public string avg_timestamp_local_datetime { get; set; }
    public string min_hour_minutes { get; set; }
    public int count { get; set; }
    public float min_air_temperature { get; set; }
    public float max_air_temperature { get; set; }
    public float avg_air_temperature { get; set; }
    public float min_battery { get; set; }
    public float max_battery { get; set; }
    public float avg_battery { get; set; }
    public int min_id { get; set; }
    public float min_illuminance { get; set; }
    public float max_illuminance { get; set; }
    public float avg_illuminance { get; set; }
    public float min_lightning_strike_average_distance { get; set; }
    public float max_lightning_strike_average_distance { get; set; }
    public float avg_lightning_strike_average_distance { get; set; }
    public int min_lightning_strike_count { get; set; }
    public int max_lightning_strike_count { get; set; }
    public float avg_lightning_strike_count { get; set; }
    public float avg_precipitation_type { get; set; }
    public int count_distinct_precipitation_type { get; set; }
    public float min_rain_accumulation_over_the_previous_minute { get; set; }
    public float max_rain_accumulation_over_the_previous_minute { get; set; }
    public float avg_rain_accumulation_over_the_previous_minute { get; set; }
    public float sum_rain_accumulation_over_the_previous_minute { get; set; }
    public float min_relative_humidity { get; set; }
    public float max_relative_humidity { get; set; }
    public float avg_relative_humidity { get; set; }
    public int min_reporting_interval { get; set; }
    public int max_reporting_interval { get; set; }
    public float avg_reporting_interval { get; set; }
    public int count_distinct_reporting_interval { get; set; }
    public float min_solar_radiation { get; set; }
    public float max_solar_radiation { get; set; }
    public float avg_solar_radiation { get; set; }
    public float min_station_pressure { get; set; }
    public float max_station_pressure { get; set; }
    public float avg_station_pressure { get; set; }
    public int min_timestamp { get; set; }
    public int max_timestamp { get; set; }
    public float avg_timestamp { get; set; }
    public float min_uv { get; set; }
    public float max_uv { get; set; }
    public float avg_uv { get; set; }
    public float min_wind_average { get; set; }
    public float max_wind_average { get; set; }
    public float avg_wind_average { get; set; }
    public int min_wind_direction { get; set; }
    public int max_wind_direction { get; set; }
    public float avg_wind_direction { get; set; }
    public float min_wind_gust { get; set; }
    public float max_wind_gust { get; set; }
    public float avg_wind_gust { get; set; }
    public float min_wind_lull { get; set; }
    public float max_wind_lull { get; set; }
    public float avg_wind_lull { get; set; }
    public int min_wind_sample_interval { get; set; }
    public int max_wind_sample_interval { get; set; }
    public float avg_wind_sample_interval { get; set; }
    public int count_distinct_wind_sample_interval { get; set; }
}
